In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving USA_Housing.csv to USA_Housing.csv
User uploaded file "USA_Housing.csv" with length 726209 bytes


In [ ]:
import io
USAhousing = pd.read_csv(io.BytesIO(uploaded['USA_Housing.csv']))
USAhousing.head(7)

Avg. Area Income  ...                                            Address
0      79545.458574  ...  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...
1      79248.642455  ...  188 Johnson Views Suite 079\nLake Kathleen, CA...
2      61287.067179  ...  9127 Elizabeth Stravenue\nDanieltown, WI 06482...
3      63345.240046  ...                          USS Barnett\nFPO AP 44820
4      59982.197226  ...                         USNS Raymond\nFPO AE 09386
5      80175.754159  ...  06039 Jennifer Islands Apt. 443\nTracyport, KS...
6      64698.463428  ...  4759 Daniel Shoals Suite 442\nNguyenburgh, CO ...

[7 rows x 7 columns]

# Training a Linear regression Model 
Let's now begin to train out regression model! We will need to first split up our data into an X array that contains the features to train on, and a y array with the target variable, in this case the Price column. We will toss out the Address column because it only has text info that the linear regression model can't use.

In [ ]:
X = USAhousing[['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
               'Avg. Area Number of Bedrooms', 'Area Population']]
y = USAhousing['Price']
'''
X_d=USAhousing.drop('address', axis=1)
X=X_d.drop('Price', axis=1).values
y=X_d.Price
'''

"\nX_d=USAhousing.drop('address', axis=1)\nX=X_d.drop('Price', axis=1).values\ny=X_d.Price\n"

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)


In [ ]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X_train,y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Model Evaluation
Let's evaluate the model by checking out it's coefficients and how we can interpret them.


In [ ]:
# print the intercept
print(lin_reg.intercept_)
coeff_df = pd.DataFrame(lin_reg.coef_, X.columns, columns=['Coefficient'])
coeff_df
#y=mx+c

-2642239.2512348383


Coefficient
Avg. Area Income                  21.570413
Avg. Area House Age           166552.477670
Avg. Area Number of Rooms     119512.534382
Avg. Area Number of Bedrooms    2758.951878
Area Population                   15.296861

# ✔️ Predictions from our Model
Let's grab predictions off our test set and see how well it did!

In [ ]:
y_pred = lin_reg.predict(X_test)
#plt.scatter(y_test, pred)
print (y_pred)

[1311074.59195064 1239575.75693463 1243916.25450739 ...  840825.86587503
 1050491.02276028  946720.46738513]


# ✔️ Regression Evaluation Metrics
Here are three common evaluation metrics for regression problems:

Mean Absolute Error (MAE) is the mean of the absolute value of the errors:
1/n∑i=1/n|yi−y^i|
 
Mean Squared Error (MSE) is the mean of the squared errors:
1/n∑i=1/n(yi−y^i)2
 
Root Mean Squared Error (RMSE) is the square root of the mean of the squared errors:
1/n∑i=1/n(yi−y^i)2−−−−−−−−−−−−√
 
📌 Comparing these metrics:

MAE is the easiest to understand, because it's the average error.
MSE is more popular than MAE, because MSE "punishes" larger errors, which tends to be useful in the real world.
RMSE is even more popular than MSE, because RMSE is interpretable in the "y" units.
All of these are loss functions, because we want to minimize them.# 

In [ ]:
from sklearn import metrics
def print_evaluate(true, predicted):  
    mae = metrics.mean_absolute_error(true, predicted)
    mse = metrics.mean_squared_error(true, predicted)
    rmse = np.sqrt(metrics.mean_squared_error(true, predicted))
    r2_square = metrics.r2_score(true, predicted)
    print('MAE:', mae)
    print('MSE:', mse)
    print('RMSE:', rmse)
    print('R2 Square', r2_square)
    print('__________________________________')

In [ ]:
test_pred = lin_reg.predict(X_test)
train_pred = lin_reg.predict(X_train)
mae = metrics.mean_absolute_error(y_test, test_pred)
print ("mean absolute error:", mae)
accuracy= metrics.r2_score(y_test, y_pred)
print(' the result is :' ,accuracy)

print('Test set evaluation:\n_____________________________________')
print_evaluate(y_test, test_pred)
print('Train set evaluation:\n_____________________________________')
print_evaluate(y_train, train_pred)

mean absolute error: 81331.22699573744
 the result is : 0.9164502014350224
Test set evaluation:
_____________________________________
MAE: 81331.22699573744
MSE: 10119734875.653522
RMSE: 100596.8929721665
R2 Square 0.9164502014350224
__________________________________
Train set evaluation:
_____________________________________
MAE: 81423.05584088489
MSE: 10292121830.714165
RMSE: 101450.09527208027
R2 Square 0.918939846901015
__________________________________


In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving insurance.csv to insurance.csv
User uploaded file "insurance.csv" with length 50264 bytes


In [ ]:
income=pd.read_csv(io.BytesIO(uploaded['insurance.csv']))
income.head()

age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [ ]:
income.shape

(1338, 7)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf_reg = RandomForestRegressor(n_estimators=1000)
rf_reg.fit(X_train, y_train)

test_pred = rf_reg.predict(X_test)
train_pred = rf_reg.predict(X_train)

accuracy= metrics.r2_score(y_test, test_pred)
print(' the result is :' ,accuracy)

 the result is : 0.8844874707348637


In [ ]:
from sklearn.svm import SVR

svm_reg = SVR(kernel='rbf', C=1000000, epsilon=0.001)
svm_reg.fit(X_train, y_train)

test_pred = svm_reg.predict(X_test)
train_pred = svm_reg.predict(X_train)
accuracy= metrics.r2_score(y_test, test_pred)
print(' the result is :' ,accuracy)

 the result is : 0.5713734365474741


In [ ]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving diabetes.csv to diabetes.csv
User uploaded file "diabetes.csv" with length 23873 bytes


In [ ]:
diabetes=pd.read_csv(io.BytesIO(uploaded['diabetes.csv']))
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
X=diabetes.drop('Outcome',axis=1).values
y=diabetes.Outcome

In [ ]:
X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=.25,stratify=y)

In [ ]:
 #Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
y_pred = gaussian.predict(X_test)
acc_gaussian = accuracy_score(y_pred, y_test)
print(acc_gaussian)
print (X_test,y_pred)
print(y_test)

0.6822916666666666
[[1.00e+00 9.70e+01 7.00e+01 ... 1.82e+01 1.47e-01 2.10e+01]
 [0.00e+00 1.52e+02 8.20e+01 ... 4.15e+01 2.70e-01 2.70e+01]
 [4.00e+00 1.22e+02 6.80e+01 ... 3.50e+01 3.94e-01 2.90e+01]
 ...
 [1.00e+00 1.44e+02 8.20e+01 ... 4.61e+01 3.35e-01 4.60e+01]
 [0.00e+00 7.30e+01 0.00e+00 ... 2.11e+01 3.42e-01 2.50e+01]
 [0.00e+00 1.07e+02 6.20e+01 ... 3.66e+01 7.57e-01 2.50e+01]] [0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 1 1 0 0 0 1 0
 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 1 1
 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0
 1 1 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1
 1 0 0 1 1 0 0]
438    0
608    0
233    0
575    0
613    0
      ..
441    0
358    0
689    1
589    0
291    1
Name: Outcome, Length: 192, dtype: int64


In [ ]:
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

decisiontree = DecisionTreeClassifier()

decisiontree.fit(X_train, y_train)
y_pred = decisiontree.predict(X_test)
acc_tree = accuracy_score(y_pred, y_test)
print(acc_tree)


0.6510416666666666


In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))


[[88 37]
 [30 37]]


In [ ]:
diabetes.shape


(768, 9)